# Generated by Django 3.2.8 on 2021-11-10 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('price', models.FloatField(verbose_name='Fiyatı')),
                ('slug', models.SlugField(unique=True)),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='İndirimli Fiyatı')),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('SP', 'Sport Wear'), ('OW', 'Out Wear')], max_length=2, verbose_name='Kategorisi')),
                ('label', models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2, verbose_name='Etiketi')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Shipping_Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('address', models.TextField(verbose_name='Açık Adres')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Sipariş Notu')),
                ('country', django_countries.fields.CountryField(default='TR', max_length=2, verbose_name='Ülke')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Ürünü',
                'verbose_name_plural': 'Sipariş Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now=True)),
                ('ordered', models.BooleanField(default=False)),
                ('paid_price', models.FloatField(blank=True, null=True)),
                ('checkout_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.shipping_addresses')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='product.OrderItem')),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'Sepet',
                'ordering': ['-ordered_date'],
            },
        ),
    ]
